#!/bin/bash
ssh root@prefx48.me "pm2 delete nodejs"

scp package.json root@prefx48.me:/home/prefx/proj/
scp -r js root@prefx48.me:/home/prefx/proj/
scp -r public root@prefx48.me:/home/prefx/proj/
scp -r html root@prefx48.me:/home/prefx/proj/

ssh root@prefx48.me "cd /home/prefx/proj; npm install"
ssh root@prefx48.me "pm2 start /home/prefx/proj/js/server.js --name nodejs"
